version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: changeme
      MONGO_INITDB_ROOT_PASSWORD: changeme
      MONGO_INITDB_DATABASE: forms
    volumes:
      - mongodb_data:/data/db
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - fb_network

  flask-backend:
    build: ./backend
    container_name: flask_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: changeme
      MONGO_INITDB_ROOT_PASSWORD: changeme
      MONGO_INITDB_DATABASE: forms
    depends_on:
      - mongodb
    networks:
      - fb_network

  frontend:
    image: nginx:alpine
    container_name: frontend
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - flask-backend
    networks:
      - fb_network

  # Optional: MongoDB Express for GUI management
  mongo-express:
    image: mongo-express:1.0.0
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: changeme
      ME_CONFIG_MONGODB_ADMINPASSWORD: changeme
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: changeme
      ME_CONFIG_BASICAUTH_PASSWORD: changeme
    depends_on:
      - mongodb
    networks:
      - fb_network

volumes:
  mongodb_data:

networks:
  fb_network:
    driver: bridge